# =========================================================================
# [SECTION 1] API 계층
# =========================================================================

#deployment영역
apiVersion: apps/v1            # Deployment API 버전
kind: Deployment               # 리소스 종류: Deployment
metadata:                      # 메타데이터
  name: myapi                  # 이 배포판의 이름을 "myapi"로 설정
spec:                          # 상세 설계
  replicas: 1                  # API 서버의 복제본 개수를 1개로 설정
  selector:                    # 관리 대상 파드 식별 조건
    matchLabels:               # 레이블 일치 확인
      app: myapi               # "app: myapi" 레이블을 가진 파드 관리
  template:                    # 파드 생성 설계도
    metadata:                  # 파드 메타데이터
      labels:                  # 파드 이름표 부여
        app: myapi             # 이름표를 "app: myapi"로 설정
    spec:                      # 컨테이너 명세
      containers:              # 컨테이너 설정
      - name: myapi            # 컨테이너 이름
        image: kimsewon/myapi:latest  # 팀에서 만든 API 서버 이미지 경로 입력
        imagePullPolicy: Always
        ports:
          - containerPort: 5000       # 컨테이너가 노출할 포트
        env:                          # API 서버가 DB에 접속하기 위한 환경변수 설정
        - name: DB_HOST               # DB 접속 주소 변수명
          value: mysql                # 위에서 만든 서비스 이름(mysql)을 주소로 사용
        - name: DB_USER               # 
          value: root                 # 
        - name: DB_PASSWORD           # DB 접속 암호 변수명
          value: "root_pw"            # DB Deployment에 설정한 암호와 동일해야 함
        - name: DB_NAME               # 
          value: admin_db             # 

#service영역
---
apiVersion: v1                 # Service API 버전
kind: Service                  # 리소스 종류: Service
metadata:                      # 메타데이터
  name: myapi                  # 웹 서버가 이 이름으로 API를 호출함
spec:                          # 서비스 설계
  type: NodePart               # 클러스터 노드의 포트를 외부로 열어 접근 가능 (ClusterIP: 클러스터 내부 전용 / LoadBalancer: 클라우드 LB 사용 가능)
  selector:                    # 대상 파드 선택
    app: myapi                 # "app: api" 레이블을 가진 파드에 연결
  ports:                       # 포트 구성
    - port: 5000               # 서비스가 외부(웹서버)로부터 받는 포트
      targetPort: 5000         # 파드 내부로 전달할 포트
      nodePort: 30001          # 클러스터 노드에서 열릴 외부 포트 (외부에서 접속할 때 사용) -> 브라우저 접속 예시: http://<EC2_PUBLIC_IP>:30001

# =========================================================================
# [SECTION 2] WEB 계층
# =========================================================================
apiVersion: apps/v1            # Deployment API 버전
kind: Deployment               # 리소스 종류: Deployment
metadata:                      # 메타데이터
  name: myweb                  # 배포판 이름을 "myweb"로 설정
spec:                          # 상세 설계
  replicas: 1                  # 웹 서버 복제본 개수 설정
  selector:                    # 관리 대상 파드 조건
    matchLabels:               # 레이블 매칭
      app: myweb               # "app: myweb" 레이블을 관리
  template:                    # 파드 설계도
    metadata:                  # 파드 메타데이터
      labels:                  # 파드 이름표
        app: myweb             # 이름표를 "app: myweb"으로 설정
    spec:                      # 컨테이너 명세
      containers:              # 컨테이너 설정
      - name: myweb            # 컨테이너 이름
        image: nginx:latest    # 팀에서 만든 프론트 이미지 경로 입력
        ports:                 # 컨테이너 포트
        - containerPort: 80    # 웹 서버(Nginx 등)의 기본 포트 80번 사용

#service영역
---
apiVersion: v1                 # Service API 버전
kind: Service                  # 리소스 종류: Service
metadata:                      # 메타데이터
  name: myweb                  # 외부 사용자가 접속할 서비스 이름
spec:                          # 서비스 설계
  type: NodePort               # [중요] 외부 사용자가 브라우저로 접속할 수 있게 NodePort 타입 사용
  selector:                    # 대상 파드 선택
    app: myweb                 # "app: myweb" 레이블을 가진 파드에 연결
  ports:                       # 포트 구성
    - port: 80                 # 서비스가 외부에서 받을 포트
      targetPort: 80           # 파드 내부로 전달할 포트
      nodePort: 30080          # 브라우저에서 <IP>:30080으로 접속 가능하도록 설정